init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd All
test: off
version: 0.0.2.{build}
artifacts:
  - path: bin
    name: petulant
deploy:
  provider: FTP
  protocol: ftp
  host: www.bear2bear.fr
  username: yoann
  password:
    secure: yq58DiRu4wPwcsvUm3gRCg==
  folder: builds\$(appveyor_build_version)
  artifact: 
